name: node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set node.js
        uses: actions/setup-node@v4
        with:
          python-version: '20'
          chache: 'npm'

      - name: install node.js
        run: npm install

      - name: run test
        run: npm test
