name: node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          chache: 'pip'

      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests flask pandas

      - name: run test
        run: pytest
